# Generated by Django 3.2 on 2021-04-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210415_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
