# Generated by Django 3.2 on 2021-04-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='my_image',
            field=models.ImageField(default='no_image.png', upload_to='images/'),
        ),
    ]
