# Generated by Django 3.2 on 2021-04-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_my_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='my_image',
            field=models.ImageField(blank=True, default='images/no_image.png', null=True, upload_to='images/'),
        ),
    ]
