# Generated by Django 3.2 on 2021-04-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='favoriteFood',
        ),
        migrations.AddField(
            model_name='profile',
            name='favoriteRecipe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='my_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
